name: Jest

on:
  pull_request:
    branches:
      - main

jobs:
  ci-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: Run Jest
        run: yarn test
