name: ESLint

on:
  pull_request:
    branches:
      - main

jobs:
  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: Run eslint
        run: eslint ./src/index.ts
